const dim = [ window.innerWidth, window.innerHeight ];
const size = 10;
module.exports.size = size;
module.exports.angleZoom = 70;
module.exports.noiseZ = 70;
module.exports.fieldForce = 100;
module.exports.dimensions = dim;
module.exports.columns = Math.ceil((dim[0] / size));
module.exports.rows = Math.ceil((dim[1] / size));