const dim=[ 200200 ];
module.exports.height = 100;
module.exports.width = 100;
module.exports.size = 5;
module.exports.angleZoom = 100;
module.exports.noiseZ = 100;
module.exports.fieldForce = 100;
module.exports.dimensions = dim;
module.exports.columns = (config.dimensions[0] / config.size);