apiVersion: apps/v1
kind: Deployment
metadata:
  name: symbiant-server
  annotations:
    kubesailEditorUid: c835dc72-c037-4d2d-ae62-7c0cd6f47b9e
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 1
  selector:
    matchLabels:
      app: symbiant
  template:
    metadata:
      name: symbiant
      labels:
        app: symbiant
    spec:
      containers:
        - name: symbiant
          image: risuki/symbiant:0.0.2
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8080"
          ports:
            - name: http
              containerPort: 8080
              hostPort: 8080
          resources:
            requests:
              cpu: 1
              memory: 1Gi
            limits:
              cpu: 2
              memory: 8Gi
