apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: symbiant-data
  labels:
    app: symbiant
  annotations:
    kubesailEditorUid: 674c02f7-955b-44cc-a52f-d42ea781e05a
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: symbiant
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: symbiant
